[meta]
version = 1
name = "Catppuccin Mocha Red"
description = "Catppuccin's darkest variant offering a cozy feeling with color-rich accents."
variant = "dark"
inherits = "vicinae-dark"
icon = "icons/catppuccin.png"

[colors.core]
accent = "#f38ba8"
accent_foreground = "#1e1e2e"
background = "#11111b"
foreground = "#cdd6f4"
secondary_background = "#181825"
border = "#1e1e2e"

[colors.main_window]
border = "#1e1e2e"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#1e1e2e"

[colors.accents]
blue = "#89b4fa"
green = "#a6e3a1"
magenta = "#cba6f7"
orange = "#fab387"
red = "#f38ba8"
yellow = "#f9e2af"
cyan = "#94e2d5"
purple = "#cba6f7"

[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#cdd6f4"
danger = "#f38ba8"
success = "#a6e3a1"
placeholder = "#cdd6f4"
selection = { background = "#313244", foreground = "#cdd6f4" }

[colors.text.links]
default = "#89b4fa"
visited = "#b4befe"

[colors.input]
border = "#1e1e2e"
border_focus = "#89b4fa"
border_error = "#f38ba8"

[colors.button.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
hover = { background = "#2ef38ba8" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#cdd6f4"
secondary_foreground = "#cdd6f4"

[colors.list.item.selection]
background = "#1e1e2e"
foreground = "#cdd6f4"
secondary_background = "#1e1e2e"
secondary_foreground = "#cdd6f4"

[colors.grid.item]
background = "#181825"
hover = { outline = "#cdd6f4" }
selection = { outline = "#cdd6f4" }

[colors.scrollbars]
background = "#1e1e2e"

[colors.loading]
bar = "#cdd6f4"
spinner = "#cdd6f4"
